/*
-- Query: SELECT * FROM store.stationary
LIMIT 0, 1000

-- Date: 2020-11-03 16:16
*/
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('apsara eraser',10,200,'eraser',1,4);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('natraj eraser',5,500,'eraser',2,5);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('camlin eraser',7,350,'eraser',3,6);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('doms eraser',8,500,'eraser',4,7);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('apsara pencil',8,300,'pencil',1,8);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('camlin pencil',7,350,'pencil',4,9);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('natraj pencil',9,278,'pencil',3,10);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('doms pencil',10,345,'pencil',2,11);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('apsara sharpener',5,237,'sharpener',1,12);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('camlin sharpener',6,344,'sharpener',2,13);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('doms sharpener',5,900,'sharpener',1,14);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('natraj harpener',4,455,'sharpener',1,15);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('natraj scale',10,700,'scale',5,16);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('camlin scale',10,300,'scale',1,17);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('doms scale',12,400,'scale',1,18);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('apsara scale',13,300,'scale',1,19);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('doms color pencils',10,250,'color pencils',1,20);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('camlin color pencils',15,350,'color pencils',2,21);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('apsara color pencils',15,400,'color pencils',3,22);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('natraj color pencils',12,233,'color pencils',1,23);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('doms sketch pens',15,456,'sketch pens',1,24);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('apsara sketch pens',16,345,'sketch pens',1,25);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('natraj sketch pens',17,345,'sketch pens',1,26);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('camlin sketch pens',18,678,'sketch pens',3,27);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('apsara wax crayons',20,765,'crayons',4,28);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('camlin crayons',22,456,'crayons',1,29);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('doms crayons',23,345,'crayons',1,30);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('natraj crayons',22,654,'crayons',1,31);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('a4 size paper',1,345,'paper',1,32);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('ruled paper',1,234,'paper',3,33);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('unruled paper',1,500,'paper',1,34);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('doms paint',30,600,'paint',5,35);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('natraj paint',30,500,'paint',6,36);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('apsara paint',35,400,'paint',7,37);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('simple calculator',60,100,'calculator',2,38);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('sci calculator',150,200,'calculator',1,39);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('white chart',5,100,'chart',2,40);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('black chart',6,234,'chart',3,41);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('blue chart',5,235,'chart',4,42);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('yellow chart',5,122,'chart',5,43);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('green chart',5,111,'chart',4,44);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('black stick pen',11,456,'stick pen',3,45);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('blue stick pen',11,233,'stick pen',4,46);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('red stick pen',11,300,'stick pen',3,47);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('green stick pen',11,400,'stick pen',2,48);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('brown stick pen',11,350,'stick pen',1,49);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('yellow stick pen',11,347,'stick pen',2,50);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('munch',5,100,'chocolate',1,51);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('kitkat',5,100,'chocolate',1,52);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('orange mittai',5,100,'chocolate',1,53);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('polo',5,100,'chocolate',1,54);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('ab scissors',20,200,'scissors',3,55);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('xy scissors',25,100,'scissors',4,56);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('stick file',10,200,'file',3,57);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('leaf file',25,100,'file',3,58);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('pen knife',15,200,'knife',3,59);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('mini pouch',20,377,'holder',4,60);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('normal pouch',25,346,'holder',4,61);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('pencil box',25,345,'holder',4,62);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('gum',15,299,'adhesive',1,63);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('glue',15,344,'adhesive',2,64);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('fevicol',10,377,'adhesive',1,65);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('fevistick',10,566,'adhesive',2,66);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('pelican',20,200,'remover',1,67);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('whitener',20,100,'remover',1,68);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('black marker',15,200,'marker',1,69);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('white marker',15,100,'marker',2,70);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('blue marker',15,100,'marker',1,71);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('red marker',15,100,'marker',2,72);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('brown sheet',30,100,'cover',4,73);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('lamination sheet',30,200,'cover',5,74);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('white chalk',100,200,'chalk piece',2,75);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('colour chalk',100,250,'chalk piece',3,76);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('short ruled',30,100,'note book',1,77);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('long ruled',50,200,'note book',1,78);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('short unruled',30,300,'note book',1,79);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('long unruled',50,100,'note book',1,80);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('sponge',10,200,'ball',2,81);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('rubber',20,50,'ball',2,82);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('plastic',25,200,'ball',2,83);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('snake/ladder',15,25,'play item',4,84);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('chess',15,25,'play item',3,85);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('business',15,35,'play item',2,86);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('ludo',15,23,'play item ',1,87);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('kitchen set',30,25,'play item',1,88);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('doctor set',30,25,'play item',1,89);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('red ink',30,33,'ink bottle',2,90);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('blue ink',30,44,'ink bottle',3,91);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('black ink',30,55,'ink bottle',4,92);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('green ink',30,34,'ink bottle',1,93);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('acrylic color',30,488,'paint',2,94);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('postor color',40,477,'paint',1,95);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('pocket dairy',15,288,'notes',1,96);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('sticky notes',15,34,'notes',2,97);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('mini note',15,222,'notes',1,98);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('envelope',5,100,'letter',2,99);
INSERT INTO `` (`item_name`,`item_price`,`item_quantity`,`item_category`,`item_discount`,`item_id`) VALUES ('inland',5,100,'letter',2,100);
